# Generated by Django 5.0.6 on 2026-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Autosave', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pc', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=65535)),
                ('af', models.IntegerField(default=0)),
                ('bc', models.IntegerField(default=0)),
                ('de', models.IntegerField(default=0)),
                ('hl', models.IntegerField(default=0)),
                ('af_alt', models.IntegerField(default=0)),
                ('bc_alt', models.IntegerField(default=0)),
                ('de_alt', models.IntegerField(default=0)),
                ('hl_alt', models.IntegerField(default=0)),
                ('ix', models.IntegerField(default=0)),
                ('iy', models.IntegerField(default=0)),
                ('i', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('iff1', models.BooleanField(default=False)),
                ('iff2', models.BooleanField(default=False)),
                ('ram', models.BinaryField()),
                ('crtc_regs', models.JSONField(default=dict)),
                ('ay_regs', models.JSONField(default=dict)),
                ('pio_regs', models.JSONField(default=dict)),
                ('screen_buffer', models.JSONField(default=list)),
                ('cursor_x', models.IntegerField(default=0)),
                ('cursor_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ROM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('BASIC', 'BASIC 1.0'), ('FIRMWARE', 'Firmware'), ('EXTENSION', 'Extension ROM')], max_length=20)),
                ('file', models.FileField(upload_to='roms/')),
                ('size', models.IntegerField()),
                ('checksum', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='tapes/')),
                ('format', models.CharField(choices=[('TAP', 'TAP'), ('CDT', 'CDT')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
